-- 코드를 작성해주세요
SELECT T3.ID
FROM ECOLI_DATA AS T1
LEFT JOIN (SELECT ID, PARENT_ID FROM ECOLI_DATA) AS T2
ON T1.ID = T2.PARENT_ID
LEFT JOIN (SELECT ID, PARENT_ID FROM ECOLI_DATA) AS T3
ON T2.ID = T3.PARENT_ID
WHERE T1.PARENT_ID IS NULL
    AND T3.ID IS NOT NULL
ORDER BY T3.ID;