-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
    ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) * 0.01, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR, 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY, 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
WHERE CAR.CAR_ID = HISTORY.CAR_ID AND CAR.CAR_TYPE = PLAN.CAR_TYPE
    AND (CAR.CAR_TYPE = '세단' OR CAR.CAR_TYPE = 'SUV')
    AND DURATION_TYPE = "30일 이상"
    AND HISTORY.CAR_ID NOT IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                  WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
GROUP BY HISTORY.CAR_ID HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
    
# 30일간의 대여 금액이 50만원 이상 200만원 미만
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
