-- 코드를 작성해주세요
WITH RANK_TABLE AS (
    SELECT ID, PERCENT_RANK()
    OVER(ORDER BY SIZE_OF_COLONY DESC) AS COLONY_SIZE
    FROM ECOLI_DATA)

SELECT ID, 
    CASE
        WHEN COLONY_SIZE <= 0.25 THEN "CRITICAL"
        WHEN COLONY_SIZE <= 0.5 THEN "HIGH"
        WHEN COLONY_SIZE <= 0.75 THEN "MEDIUM"
    ELSE "LOW" END AS COLONY_NAME
FROM RANK_TABLE
ORDER BY ID;