-- 코드를 입력하세요
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE like 'Intact%'
 AND (SEX_UPON_OUTCOME like 'Neutered %' OR SEX_UPON_OUTCOME like 'Spayed%')
GROUP BY ANIMAL_ID;