-- 코드를 입력하세요
SELECT T1.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    ROUND(SUM(REVIEW_SCORE)/COUNT(T2.REST_ID), 2) AS SCORE
FROM REST_INFO AS T1, REST_REVIEW AS T2
WHERE T1.REST_ID = T2.REST_ID
    AND T1.ADDRESS LIKE "서울%"
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;