-- 코드를 작성해주세요
# 1) 1세대 쿼리만 생성
# 2) RECURSIVE를 통해 재귀 쿼리 완성
WITH RECURSIVE T1 AS(SELECT ID, PARENT_ID, 1 AS GENERATION 
                     FROM ECOLI_DATA
                     WHERE PARENT_ID IS NULL
UNION ALL 
                    SELECT T2.ID, T2.PARENT_ID, 1+T1.GENERATION AS GENERATION
                    FROM ECOLI_DATA AS T2
                    INNER JOIN T1 ON T1.ID = T2.PARENT_ID)

SELECT COUNT(ID) AS COUNT, GENERATION 
FROM T1
WHERE NOT ID IN (SELECT DISTINCT PARENT_ID
                FROM ECOLI_DATA
                WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION 
ORDER BY GENERATION ASC;
