-- 코드를 작성해주세요
WITH RECURSIVE T1 AS (
    # NON-Recursive
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    # Recursive
    SELECT T2.ID, T2.PARENT_ID, T1.GENERATION + 1 
    FROM T1
    JOIN ECOLI_DATA AS T2
    ON T1.ID = T2.PARENT_ID)

SELECT COUNT(*) AS COUNT, GENERATION
FROM T1
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM T1
    WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;