-- 코드를 입력하세요
SELECT CAR_ID, CASE WHEN END_DATE >= '2022-10-16' THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
WHERE END_DATE IN (SELECT MAX(END_DATE) 
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2 
                WHERE T1.CAR_ID = T2.CAR_ID 
                    AND START_DATE <= '2022-10-16'
                GROUP BY CAR_ID)
ORDER BY CAR_ID DESC;

