-- 코드를 입력하세요
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.NAME IS NOT NULL AND ANIMAL_OUTS.NAME IS NULL
ORDER BY ANIMAL_INS.DATETIME ASC
LIMIT 3;