-- 코드를 입력하세요
SELECT T2.PRODUCT_ID, T2.PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS T1
LEFT JOIN FOOD_PRODUCT AS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05-%"
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;


