-- 코드를 입력하세요
SELECT HISTORY_ID, 
    ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 
    0.01 * (100 - IFNULL((SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = 
                  (CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
                        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
                        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
                    END)), 0)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR, 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY, 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
WHERE CAR.CAR_ID = HISTORY.CAR_ID AND CAR.CAR_TYPE = PLAN.CAR_TYPE
    AND CAR.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;
          
          



