-- 코드를 입력하세요
SELECT HISTORY_ID, 
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN ROUND(DAILY_FEE * 0.85 * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN ROUND(DAILY_FEE * 0.92 * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN ROUND(DAILY_FEE * 0.95 * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
        ELSE ROUND((DAILY_FEE) * (DATEDIFF(END_DATE, START_DATE) + 1), 0)
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR, 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY, 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
WHERE CAR.CAR_ID = HISTORY.CAR_ID AND CAR.CAR_TYPE = PLAN.CAR_TYPE
    AND CAR.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;