-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT, DOCTOR, APPOINTMENT
WHERE PATIENT.PT_NO = APPOINTMENT.PT_NO AND DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
    AND APNT_CNCL_YN = 'N' AND APNT_YMD like '2022-04-13%'
ORDER BY APNT_YMD ASC;