-- 코드를 입력하세요
WITH MAX_MEMBER AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1) 

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE
RIGHT JOIN MAX_MEMBER
ON MEMBER_PROFILE.MEMBER_ID = MAX_MEMBER.MEMBER_ID
LEFT JOIN REST_REVIEW
ON REST_REVIEW.MEMBER_ID = MAX_MEMBER.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;