-- 코드를 작성해주세요
SELECT T2.ITEM_ID, T3.ITEM_NAME, T3.RARITY
FROM ITEM_INFO T1
LEFT JOIN ITEM_TREE T2
ON T1.ITEM_ID = T2.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO T3
ON T2.ITEM_ID = T3.ITEM_ID
WHERE T1.RARITY = "RARE" AND T2.ITEM_ID IS NOT NULL
ORDER BY ITEM_ID DESC;