-- 코드를 입력하세요
SELECT 
    MONTH(T1.START_DATE) AS MONTH, 
    T1.CAR_ID, 
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
JOIN 
    (
        SELECT 
            CAR_ID
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
        GROUP BY 
            CAR_ID
        HAVING 
            COUNT(*) >= 5
    ) AS T2
ON 
    T1.CAR_ID = T2.CAR_ID
WHERE 
    START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
GROUP BY 
    MONTH(T1.START_DATE), T1.CAR_ID
HAVING 
    COUNT(*) > 0
ORDER BY 
    MONTH ASC, CAR_ID DESC;
