-- 코드를 작성해주세요
WITH MAX_LENGTH AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR)

SELECT YEAR(T1.DIFFERENTIATION_DATE) AS YEAR,
    T2.SIZE_OF_COLONY - T1.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS T1
JOIN MAX_LENGTH AS T2
ON YEAR(T1.DIFFERENTIATION_DATE) = T2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
    