-- 코드를 입력하세요
SELECT DISTINCT COMPANY.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS COMPANY, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
WHERE COMPANY.CAR_ID = HISTORY.CAR_ID
    AND CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;