-- 코드를 입력하세요
SELECT DISTINCT T1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR T1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
ON T1.CAR_ID = T2.CAR_ID
WHERE CAR_TYPE = '세단' 
    AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;