-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS F
LEFT JOIN FISH_NAME_INFO 
ON F.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE LENGTH IN (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = F.FISH_TYPE GROUP BY FISH_TYPE)
ORDER BY ID ASC;


 
