-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, E_T.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_DEPARTMENT AS D_T, HR_EMPLOYEES AS E_T, HR_GRADE AS G_T
WHERE D_T.DEPT_ID = E_T.DEPT_ID 
    AND E_T.EMP_NO = G_T.EMP_NO
    AND YEAR = "2022"
GROUP BY EMP_NO HAVING MAX(SCORE)
ORDER BY SCORE DESC 
LIMIT 1;
    