-- 코드를 입력하세요
SELECT TITLE, U_B.BOARD_ID, U_R.REPLY_ID, U_R.WRITER_ID, U_R.CONTENTS, 
    DATE_FORMAT(U_R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS U_B
INNER JOIN USED_GOODS_REPLY AS U_R
ON U_B.BOARD_ID = U_R.BOARD_ID
WHERE U_B.CREATED_DATE LIKE '2022-10%'
ORDER BY U_R.CREATED_DATE, TITLE;